# Generated by Django 4.1.7 on 2023-04-01 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=300)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunity.trip')),
            ],
        ),
    ]
