# Generated by Django 4.1.7 on 2023-04-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunity', '0002_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='direction',
            field=models.IntegerField(choices=[[0, 'from squ'], [1, 'to squ']]),
        ),
    ]
